### ISSUE TITLE
ProPlates not displaying on catcatnya.com and other glitch-soc instances

### ISSUE THREAD

**Issue by ItsVipra** [ItsVipra/ProToots#10]
Site is recognized as Mastodon, but no column is found.  
Either some difference in class names or async stuff.

Will have to create an account to investigate.

**Comment by chloe-the-catgirl** [comment]
The source code of catcatnya [can be found here](https://git.kescher.at/CatCatNya/catstodon). I'll setup a local instance and experiment with it.

**Comment by chloe-the-catgirl** [comment]
Kinda fascinating. It works locally. But the current code is kinda flaky, we definitely should work on that.

**Comment by ItsVipra** [comment]
that is really weird, seeing as i tested it on your instance and have also gotten reports from your users that it is indeed working.
this may be a silly question, but have you reloaded the page since installing the addon?

**Comment by ItsVipra** [comment]
that is so weird, glad it's working now...
definitely something I'll keep in mind for future version, thanks for the report
