### ISSUE TITLE
pixelfed has native pronoun support, let's use that

### ISSUE THREAD

**Issue by ItsVipra** [ItsVipra/ProToots#30]
Annoucement posts:
https://mastodon.social/@pixelfed/106220703638290928
https://pixelfed.social/site/newsroom/2021/06/profile-pronouns

sadly the API documentation is just not 🙃
https://docs.pixelfed.org/technical-documentation/activitypub/#profiles

so i'd say low priority on this one, unless you want to rummage through the source code and API responses

**Comment by chloe-the-catgirl** [comment]
Unfortunately, the pronouns do not seem to federate. Either we always interact with the remote instance for querying the API, or we simply ignore it. It's a bummer that we cannot access those fields easily. :disappointed:

**Comment by ItsVipra** [comment]
well darn that's a shame :c
honestly i don't really feel like querying the remote instance, plus the amount of pixelfed users (at least in my feed) is very small
maybe something for when we expand support, but for now bio and fields will have to make do
