### ISSUE TITLE
Move the plate out of the profile name

### ISSUE THREAD

**Issue by nachtjasmin** [ItsVipra/ProToots#33]
Right now, we add an anchor inside an anchor. **This is a major accessibility issue.**

We should not add the plate to the same `a` tag as the name, it should be clickable on its own.

**Comment by ItsVipra** [comment]
i don't see how the first is related to the second, but extracting out of the display name is basically the same as #1

**Comment by chloe-the-catgirl** [comment]
maybe I wasn't clear enough, does the edited description help? ^^

**Comment by ItsVipra** [comment]
as in make it a sibling of `strong.display-name__html`? yeah we can do that, just gotta make sure it still looks nice then :3
