### ISSUE TITLE
new field matcher matches less than before

### ISSUE THREAD

**Issue by ItsVipra** [ItsVipra/ProToots#39]
Note: matches less than before in some instances, i.E. partial fieldname matches (ex: "pronouns EN")

_Originally posted by @se4598 in https://github.com/ItsVipra/ProToots/pull/38#discussion_r1252328545_
            
whoopsie daisy i messed up.
what if we just use two nested loops instead?
makes the runtime n^2 but uuuhhh

**Comment by nachtjasmin** [comment]
or we transform the patterns into regexes, that's also quick and easy to do. ^^

**Comment by ItsVipra** [comment]
wouldn't that result in something like `\w*pronoun|professional nouns|pronomen\w*` though? getting longer with each language/exception?

**Comment by nachtjasmin** [comment]
I would've just multiple patterns instead of one big one. :D

**Comment by ItsVipra** [comment]
closed in 8d5e1573121fabc4f06fa12df3cf57a386076808
(two loops method)
