### ISSUE TITLE
Publish the extension to common stores

### ISSUE THREAD

**Issue by chloe-the-catgirl** [ItsVipra/ProToots#4]
The extension should be published at least for:

- [ ] Firefox (in progress)
- [ ] Chrome

Microsoft Edge and the other Chrome derivates should be automatically covered by that.

**Comment by ItsVipra** [comment]
When trying to run the addon in Chrome (113.0.5672.127) there are several problems at the moment:
1. The 'browser_specific_settings' manifest key is not recognized
2. Manifest v2 is no longer supported in chrome
3. "browser" is not defined - use "chrome" instead of generic browser?

**Comment by chloe-the-catgirl** [comment]
1. and 2. should be fixable.

3. sounds like a Google thing. I hope it solves itself without further changes after we've migrated to manifest v3, but it's just a hope. :D

**Comment by ItsVipra** [comment]
closing this, as that seems pretty obvious :D
if you want to know more about progress towards store releases [check the milestones](https://github.com/ItsVipra/ProToots/milestones)
