### ISSUE TITLE
Names disappear in follow-list

### ISSUE THREAD

**Issue by se4598** [ItsVipra/ProToots#49]
(in advanced view) On the following or followers-list of a profile the ProPlate on a entry causes the display name of the account in the entry to be shorted up to the point that the name isn't visible at all (not even ellipsis) when a long pronoun-plate is displayed.

this is especially inconsistent to the normal view where the display name has priority (width-wise) over the ProPlate.

**Comment by nachtjasmin** [comment]
Oh, good catch. Are you using a development version you've compiled yourself or the one that's released on the Mozilla addon store?

**Comment by se4598** [comment]
> Are you using a development version you've compiled yourself or the one that's released on the Mozilla addon store?

released via mozilla
