### ISSUE TITLE
Sanitize HTML special characters

### ISSUE THREAD

**Issue by ItsVipra** [ItsVipra/ProToots#55]
Because we no longer set innerHTML characters such as `&` are displayed as `&amp;` instead.
![image](https://github.com/ItsVipra/ProToots/assets/24212409/c294c099-4ae2-45a5-9910-c2915ef51084)

**Comment by nachtjasmin** [comment]
I think, we should do a simple string replacement for that and [other codes that might be escaped as well](https://en.m.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references).

**Comment by se4598** [comment]
simple string replacement might be not enough. I'm sure that was a link before ;)
![grafik](https://github.com/ItsVipra/ProToots/assets/1153763/d8f3ca10-a4ff-46ee-8aea-eaa124fc71cf)

**Comment by nachtjasmin** [comment]
clearing the cache should help, if not: please send us the profile so I can investigate that ^^

**Comment by se4598** [comment]
> clearing the cache should help

yup, apparently old cache entry , and with #56 it prob. won't happen again :+1:
