### ISSUE TITLE
Someone else's pronoun tag gets duplicated on random users (sometimes twice)

### ISSUE THREAD

**Issue by mxamber** [ItsVipra/ProToots#65]
1 screenshot says more than 1000 words:

![Four different likes and boosts in my notifications, all of which have "she/her or bun" as the pronoun tag behind their name - twice.](https://github.com/ItsVipra/ProToots/assets/13611718/054c3865-1cfc-4f1c-b806-ea7d86b5bc39 "Four different likes and boosts in my notifications, all of which have 'she/her or bun' as the pronoun tag behind their name - twice.")

I can't determine WHOSE pronouns those are; could be one of the people I follow, could be anyone's who showed up once on my timeline. Happens only in notifications, as far as I can tell, and ~~*apparently* (no guarantees) for people who don't have a pronoun field in their bio table~~ if someone already has pronouns in their bio, they sometimes get this misplaced tag added after their own. Most people with working pronoun tags are fine, though.

![A "a poll you have voted in" notification. The poster's own "she/her" tag has a "she/her or bun" tag misalignedly added after it.](https://github.com/ItsVipra/ProToots/assets/13611718/4d1d4780-bfb1-4207-a149-5f7468d52a3b "A 'a poll you have voted in' notification. The poster's own 'she/her' tag has a 'she/her or bun' tag misalignedly added after it.")

Firefox 115.0.2
ProToots 1.2.1 (last updated July 18)

The blue styling of the tags is a userstyle I wrote, but it happens with or without that script regardless.

**Comment by nachtjasmin** [comment]
Thanks for your report, I'm wondering if it's some race condition that only appears on glitch-soc. But so far I'm lucky that it's only happening on the notifications ^^

Gonna look into this tomorrow :3

**Comment by ItsVipra** [comment]
was able to reproduce, think i see what's going wrong as well 
![image](https://github.com/ItsVipra/ProToots/assets/24212409/537598d1-358b-4c21-a274-680059f3d9e8)

but yeah first it's eepy time
thanks for the report :3
