### ISSUE TITLE
Currently failing on latest glitch-soc (v4.3.0-alpha.3+glitch)

### ISSUE THREAD

**Issue by kescherCode** [ItsVipra/ProToots#77]
I get the following stacktrace on up-to-date glitch-soc based instances:

```
TypeError: ActionElement.closest(...) is null protootshelpers.js:56:16
    addTypeAttribute protootshelpers.js:56
    addtoTootObserver protoots.js:152
    main protoots.js:107
    forEach self-hosted:157
    main protoots.js:107
```

**Comment by ItsVipra** [comment]
Thanks for the report keschi <3 

Seems like the extension is trying to add pronouns to the indicator showing the currently logged-in user. It matches on the "account" class, which must have been recently added to that element.
Adding a `if (hasClasses(ActionElement, "account--minimal")) return;` somewhere in the stack should resolve the type error. I'll look for a nice place to put that later today :3

**Comment by ItsVipra** [comment]
In the meantime, I've also noticed that clicking on somebody's username to open their profile and then navigating back causes two ProPlates to be added to some (*but not all*) usernames :woozy_face:
