### ISSUE TITLE
Add unit tests for parts of the functionality

### ISSUE THREAD

**Issue by nachtjasmin** [ItsVipra/ProToots#8]
## Reasoning

We can test several parts of the plugin with unit tests. For example:

- Extracting pronouns from the bio
- calling pronouns.page
- different types of field inputs and their outputs

This should increase our confidence in the code base. At a later point, we can also add integration tests against specific web pages, although I think that extensive end to end tests might be hard to implement.

**Comment by ItsVipra** [comment]
one major issue is that webextension-polyfill only runs in browsers, so it will fail any test it is imported into

**Comment by nachtjasmin** [comment]
The polyfill issue is going to be closed with #15.
